version: '3.8'

# Development-optimized docker-compose configuration
# This file is optimized for faster builds and development workflow

services:
  # Backend API Server (Development Optimized)
  backend:
    image: mppw-mcp-backend:dev
    container_name: mppw-mcp-backend-dev
    build:
      context: .
      dockerfile: backend/Dockerfile
      cache_from:
        - mppw-mcp-backend:latest
        - mppw-mcp-backend:dev
      args:
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: development
    ports:
      - "8000:8000"
    env_file:
      - ./config/debug.env
    environment:
      - GROQ_API_KEY=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
      - OPENROUTER_API_KEY=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
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DATABASE=mppw_mcp
      - DATA_MONGODB_URL=mongodb://mongo_data:27017
      - DATA_MONGODB_DATABASE=mppw_content
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_DEFAULT_MODEL=phi3:mini
      - REDIS_URL=redis://redis:6379
      - ENV=development
      - SECRET_KEY=supersecretkey123
      - PYTHONPATH=/app
    depends_on:
      - mongo
      - mongo_data
      - redis
      - ollama
      - neo4j
    volumes:
      - ./backend:/app/backend
      - ./config:/app/config
      - ./logs:/app/logs
      # Exclude node_modules and other heavy directories
      - /app/frontend/node_modules
      - /app/backend/venv
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["python", "-m", "uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/backend"]

  # Frontend Vue.js Application (Development Optimized)
  frontend:
    image: mppw-mcp-frontend:dev
    container_name: mppw-mcp-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - mppw-mcp-frontend:latest
        - mppw-mcp-frontend:dev
      args:
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: development
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Ollama AI Model Server (Development Optimized)
  ollama:
    image: ollama/ollama:latest
    container_name: mppw-mcp-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_dev:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g

  # MongoDB Database (Development Optimized)
  mongo:
    image: mongo:7
    container_name: mppw-mcp-mongo-dev
    environment:
      - MONGO_INITDB_DATABASE=mppw_mcp
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db
      - ./backend/database/init.js:/docker-entrypoint-initdb.d/init.js
    restart: unless-stopped

  # Secondary MongoDB for content data (Development Optimized)
  mongo_data:
    image: mongo:7
    container_name: mppw-mcp-mongo-data-dev
    environment:
      - MONGO_INITDB_DATABASE=mppw_content
    ports:
      - "27018:27017"
    volumes:
      - mongo_content_dev_data:/data/db
      - ./backend/database/seed_content.js:/docker-entrypoint-initdb.d/seed_content.js
    restart: unless-stopped

  # Redis for Caching and Session Management (Development Optimized)
  redis:
    image: redis:7-alpine
    container_name: mppw-mcp-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Neo4j Database (Development Optimized)
  neo4j:
    image: neo4j:5.19
    container_name: mppw-mcp-neo4j-dev
    ports:
      - "7474:7474"  # http
      - "7687:7687"  # bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_dev_data:/data
    restart: unless-stopped

volumes:
  mongo_dev_data:
  redis_dev_data:
  ollama_dev:
  mongo_content_dev_data:
  neo4j_dev_data:

networks:
  default:
    name: mppw-mcp-dev-network 